version: "3.3"
services:

  app:
    container_name: jira-bot-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=${POSTGRES_URL}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TELEGRAM_BOT_NAME=${TELEGRAM_BOT_NAME}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - SPRING_ACTIVE_PROFILES=prod
      - API_TOKEN=${API_TOKEN}
    env_file:
      - src/main/resources/config/.env
    ports:
      - "8181:8080"
    restart: always
    networks:
      - jira-bot-network

networks:
  jira-bot-network:
    driver: bridge
